#!/bin/bash
### BEGIN INIT INFO
# Provides:   ut2004
# Required-Start: $local_fs $remote_fs screen-cleanup
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:    UT2004 server
# Description:    Script managing the Unreal Tournament 2004 server
### END INIT INFO

#Settings
SERVICE='ucc-bin'
OPTIONS='-nohomedir -langame'
USER='ut2004'
SCREENSESSION="ut2004"
INITIALMAP='ONS-Torlan'
GAMETYPE='Onslaught.ONSOnslaughtGame'
UTPATH='/opt/UT2004/System'
HISTORY=1024

ADMINLOGIN='admin'
ADMINPASSPATH='/root/admin_pass.txt'

# Fetch admin password
ADMINPASS=`cat $ADMINPASSPATH`
INVOCATION="./ucc-bin server ${INITIALMAP}?game=${GAMETYPE}?AdminName=${ADMINLOGIN}?AdminPassword=${ADMINPASS} $OPTIONS"

start_service() {
    su - $USER -c "cd $UTPATH; tmux new-session -s \"$SCREENSESSION\" -d \"$INVOCATION\""
}

stop_service() {
    su - $USER -c "tmux kill-session -t \"$SCREENSESSION\""
}

#Start-Stop here
case "$1" in
    start)
        start_service
    ;;
    stop)
        stop_service
    ;;
    restart)
        stop_service
        start_service
    ;;
    status)
       if su - c $USER "tmux ls | grep -q ^$SCREENSESSION:"; then
           echo "$SERVICE is running."
       else
           echo "$SERVICE is not running."
       fi
    ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
    ;;
esac

exit 0
