#!/bin/bash 
### BEGIN INIT INFO
# Provides:   ut2004
# Required-Start: $local_fs $remote_fs screen-cleanup
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:    UT2004 server
# Description:    Script managing the Unreal Tournamnet 2004 server
### END INIT INFO
 
#Settings
SERVICE='ucc-bin'
OPTIONS='-nohomedir -langame'
USER='ut2004'
SCREENSESSION="ut2004"
INITIALMAP='ONS-Torlan'
GAMETYPE='Onslaught.ONSOnslaughtGame'
UTPATH='/opt/UT2004/System'
HISTORY=1024

ADMINLOGIN='login'
ADMINPASSPATH='/root/webui_pass.txt'

# Fetching the WebUI password
if [[ -e $ADMINPASSPATH && ! -f $ADMINPASSPATH ]];then
    rm -rf $ADMINPASSPATH
fi
if [[ ! -e $ADMINPASSPATH ]];then
    echo "Generating a new password, check $ADMINPASSPATH"
    openssl rand -base64 32 > $ADMINPASSPATH
    chmod a-rwx $ADMINPASSPATH
fi

ADMINPASS=`cat $ADMINPASSPATH`
INVOCATION="./ucc-bin server ${INITIALMAP}?game=${GAMETYPE}?AdminName=${ADMINLOGIN}?AdminPassword=${ADMINPASS} $OPTIONS"

start_service() {
    su - $USER -c "cd $UTPATH; screen -h $HISTORY -dmS $SCREENSESSION $INVOCATION"
}
 
stop_service() {
    su - $USER -c "screen -p 0 -S $SCREENSESSION -X quit"
} 
  
#Start-Stop here
case "$1" in
    start)
        start_service
    ;;
    stop)
        stop_service
    ;;
    restart)
        stop_service
        start_service
    ;;
    status)
       if pgrep -u $USER -f $SERVICE > /dev/null; then
           echo "$SERVICE is running."
       else
           echo "$SERVICE is not running."
       fi
    ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
    ;;
 esac
 
 exit 0
