#!/bin/bash
### BEGIN INIT INFO
# Provides:          tmnf
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop tmnf as daemon
### END INIT INFO

## Username to run tmnf under
USER="tmnf"

SCREENSESSION_TM="tmnf"
SCREENSESSION_ASECO="aseco"

INVOCATION_TM="./RunTrackmaniaNations.sh"
INVOCATION_ASECO="./Aseco.sh"

PATH="/home/tmnf/serverfiles"

start_service() {
    su - $USER -c "cd $PATH; tmux new-session -s \"$SCREENSESSION_TM\" -d \"$INVOCATION_TM\""
    su - $USER -c "cd $PATH; tmux new-session -s \"$SCREENSESSION_ASECO\" -d \"$INVOCATION_ASECO\""
}

stop_service() {
    su - $USER -c "tmux kill-session -t \"$SCREENSESSION_ASECO\""
    su - $USER -c "tmux kill-session -t \"$SCREENSESSION_TM\""
    bash /etc/vz-template/export_tmnf_db.sh
}

#Start-Stop here
case "$1" in
    start)
        start_service
    ;;
    stop)
        stop_service
    ;;
    restart)
        stop_service
        start_service
    ;;
    status)
       if su - c $USER "tmux ls | grep -q ^$SCREENSESSION_TM:"; then #YOLO
           echo "$SERVICE is running."
       else
           echo "$SERVICE is not running."
       fi
    ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
    ;;
esac

exit 0
