#!/bin/bash -e
### BEGIN INIT INFO
# Provides:          tmnf
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop tmnf as daemon
### END INIT INFO

USER="tmnf"
GROUP="tmnf"

NAME_TMNF=tmnf
NAME_ASECO=aseco

PATH_TMNF="/home/tmnf/serverfiles"

PIDFILE_TMNF="$PATH_TMNF/TrackmaniaServer.pid"
PIDFILE_ASECO="$PATH_TMNF/aseco.pid"

DAEMON_TMNF="$PATH_TMNF/TrackmaniaServer.sh"
DAEMON_ASECO="$PATH_TMNF/aseco.sh"

case "$1" in
    start)
        chown -R $USER:$GROUP $PATH_TMNF
        echo -n "Starting daemon: $NAME_TMNF"
        start-stop-daemon --start --quiet --pidfile "$PIDFILE_TMNF" --chdir "$PATH_TMNF" --chuid "$USER" --exec "$DAEMON_TMNF"
        echo "."

        sleep 2s #YOLO

        echo -n "Starting daemon: $NAME_ASECO"
        start-stop-daemon --start --quiet --pidfile "$PIDFILE_ASECO" --chdir "$PATH_TMNF" --chuid "$USER" --exec "$DAEMON_ASECO"
        echo "."
    ;;
    stop)
        echo -n "Stopping daemon: $NAME_ASECO"
        start-stop-daemon --stop --quiet --pidfile "$PIDFILE_ASECO"
        echo "."

        echo -n "Stopping daemon: $NAME_TMNF"
        start-stop-daemon --stop --quiet --pidfile "$PIDFILE_TMNF"
        echo "."

        echo -n "Exporting database: $USER"
        bash /etc/vz-template/export_tmnf_db.sh
        echo "."
    ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
