#!/bin/bash
# /etc/init.d/minecraft

### BEGIN INIT INFO
# Provides:   minecraft
# Required-Start: $local_fs $remote_fs screen-cleanup
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:    Minecraft server
# Description:    Starts the minecraft server
### END INIT INFO

#Settings
SERVICE='minecraft_server.jar'
OPTIONS='nogui'
MCPATH='/home/minecraft/server/'
MAXHEAP=1920 # 128MB for the OS
MINHEAP=1664
USER='minecraft'
SCREENSESSION="minecraft"
HISTORY=1024
INVOCATION="java -Xmx${MAXHEAP}M -Xms${MINHEAP}M -XX:+UseConcMarkSweepGC -jar $SERVICE $OPTIONS"

start_service() {
    su - $USER -c "screen -h $HISTORY -dmS $SCREENSESSION $INVOCATION"
}

stop_service() {
    su - $USER -c "screen -p 0 -S $SCREENSESSION -X quit"
}

#Start-Stop here
case "$1" in
    start)
        su - $USER -c "cd $MCPATH; screen -h $HISTORY -dmS $SCREENSESSION $INVOCATION"
    ;;
    stop)
        su - $USER -c "screen -p 0 -S $SCREENSESSION -X quit"
    ;;
    restart)
        stop_service
        start_service
    ;;
    status)
        if su - c $USER "screen -ls | grep -q $SCREENSESSION"; then
            echo "$SERVICE is running."
        else
            echo "$SERVICE is not running."
        fi
    ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
    ;;
 esac

 exit 0
